# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7230840263e0cbb8e6c361bdc4f3a12192c3f9e97e9cc902f7e11ac57731b84545840e6a64ceaf1fb4cc698ef7b11ef8ca201914aef8c7a10a199ffd719c234

test:
  secret_key_base: fd703112e979bd338ea42a907794fe0324d0f894f44358b274d836b58b9e18922b6f866db577ae224eb3717853dc8a91a20e1d68ac7d82325400002575ba01ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
